<?php

declare(strict_types=1);

/* Phase 2F.3 synthetic test-schema probe. No HTTP, migrations, or production fallback. */
require dirname(__DIR__, 3) . '/cpanel-root/private/livescore/app/bootstrap/autoload.php';

use Araucaria\Livescore\Config\DatabaseUrl;
use Araucaria\Livescore\Database\DatabaseSafety;
use Araucaria\Livescore\Database\PdoConnectionFactory;
use Araucaria\Livescore\Ingestion\PdoIngestionRepository;
use Araucaria\Livescore\Ingestion\NormalizedIngestionService;
use Araucaria\Livescore\Ingestion\NormalizedScoreObservation;
use Araucaria\Livescore\Ingestion\RedactedReceipt;
use Araucaria\Livescore\Support\Sha256;
use Araucaria\Livescore\Support\StructuredLogger;

if (getenv('PHP_COLLECTOR_TEST_ONLY') !== '1') throw new RuntimeException('Refusing probe without PHP_COLLECTOR_TEST_ONLY=1.');
$url = getenv('DATABASE_URL'); if (!is_string($url) || $url === '') throw new RuntimeException('DATABASE_URL is required.');
$config = DatabaseUrl::parse($url); DatabaseSafety::requireUrlDatabase($config, DatabaseSafety::PERCONA57_TEST_DATABASE);
$pdo = PdoConnectionFactory::create($config); DatabaseSafety::requireTestDatabase($pdo, $config);
$tag = 'php-2f3-' . bin2hex(random_bytes(8));
$ids = ['contest'=>null,'otherContest'=>null,'otherCategory'=>null,'sourceA'=>null,'sourceB'=>null,'rawA'=>null,'rawB'=>null,'entries'=>[],'snapshots'=>[]];
$scenarios = array_fill_keys(['ineligible','initial','newer','equal_timestamp','reset','out_of_order','out_of_order_dedup','cross_source_deferred','service_orchestration'], false);
$cleaned = false;
try {
    $now = '2026-09-14 14:00:00.000001'; setup($pdo, $ids, $tag, $now); $repo = new PdoIngestionRepository($pdo);
    $entry = entry($pdo,$ids,$tag.'-main',$now); $ids['entries'][]=$entry;
    $unzoned = snapshot($pdo,$ids,$entry,$ids['sourceA'],null,'UNZONED_SOURCE_TEXT','10','u',$now); $ids['snapshots'][]=$unzoned;
    ok($repo->reconcileAcceptedSnapshot($unzoned,'2026-09-14 14:01:00.000001')->outcome==='INELIGIBLE_TIMESTAMP' && countOf($pdo,'SELECT COUNT(*) FROM canonical_score_events WHERE score_snapshot_id=?',[$unzoned])===0 && countOf($pdo,'SELECT COUNT(*) FROM current_scores WHERE entry_id=?',[$entry])===0 && countOf($pdo,'SELECT COUNT(*) FROM score_snapshot_flags WHERE snapshot_id=?',[$unzoned])===0,'ineligible'); $scenarios['ineligible']=true;
    $initial = snapshot($pdo,$ids,$entry,$ids['sourceA'],'2026-09-14 14:00:00.000001','CONFIRMED_UTC','100','i',$now); $ids['snapshots'][]=$initial; $initialAt='2026-09-14 14:01:00.000001'; $initialResult=$repo->reconcileAcceptedSnapshot($initial,$initialAt); ok($initialResult->outcome==='CANONICAL_INITIAL' && $initialResult->canonicalEventId!==null,'initial result'); $event1=one($pdo,'SELECT * FROM canonical_score_events WHERE id=?',[$initialResult->canonicalEventId]); ok((string)$event1['entry_id']===$entry&&(string)$event1['score_snapshot_id']===$initial&&$event1['selected_at']===$initialAt&&$event1['effective_at']==='2026-09-14 14:00:00.000001'&&$event1['selection_basis']==='SINGLE_SOURCE_SEQUENCE'&&$event1['selection_reason']==='INITIAL_CANONICAL'&&$event1['context']===null,'initial event'); ok((string)scalar($pdo,'SELECT canonical_snapshot_id FROM current_scores WHERE entry_id=?',[$entry])===$initial,'initial pointer');$scenarios['initial']=true;
    $newer=snapshot($pdo,$ids,$entry,$ids['sourceA'],'2026-09-14 14:00:01.000001','CONFIRMED_UTC','101','n',$now);$ids['snapshots'][]=$newer;$newerResult=$repo->reconcileAcceptedSnapshot($newer,'2026-09-14 14:01:01.000001');ok($newerResult->outcome==='CANONICAL_ADVANCED'&&countOf($pdo,'SELECT COUNT(*) FROM canonical_score_events WHERE entry_id=?',[$entry])===2&&(string)scalar($pdo,'SELECT selection_reason FROM canonical_score_events WHERE id=?',[$newerResult->canonicalEventId])==='SAME_SOURCE_NONDECREASING_EFFECTIVE_AT'&&(string)scalar($pdo,'SELECT canonical_snapshot_id FROM current_scores WHERE entry_id=?',[$entry])===$newer&&(string)scalar($pdo,'SELECT score_snapshot_id FROM canonical_score_events WHERE id=?',[$initialResult->canonicalEventId])===$initial,'newer append-only');$scenarios['newer']=true;
    $equal=snapshot($pdo,$ids,$entry,$ids['sourceA'],'2026-09-14 14:00:01.000001','CONFIRMED_UTC','102','e',$now);$ids['snapshots'][]=$equal;$equalResult=$repo->reconcileAcceptedSnapshot($equal,'2026-09-14 14:01:02.000001');ok($equalResult->outcome==='CANONICAL_ADVANCED'&&(string)scalar($pdo,'SELECT canonical_snapshot_id FROM current_scores WHERE entry_id=?',[$entry])===$equal&&countOf($pdo,'SELECT COUNT(*) FROM canonical_score_events WHERE entry_id=?',[$entry])===3,'equal advance');$scenarios['equal_timestamp']=true;
    $reset=snapshot($pdo,$ids,$entry,$ids['sourceA'],'2026-09-14 14:00:02.000001','CONFIRMED_UTC','0','r',$now);$ids['snapshots'][]=$reset;$resetResult=$repo->reconcileAcceptedSnapshot($reset,'2026-09-14 14:01:03.000001');ok($resetResult->outcome==='CANONICAL_ADVANCED'&&(string)scalar($pdo,'SELECT score FROM score_snapshots WHERE id=?',[$reset])==='0','reset advance');$scenarios['reset']=true;
    $beforeEvent=countOf($pdo,'SELECT COUNT(*) FROM canonical_score_events WHERE entry_id=?',[$entry]);$beforePointer=one($pdo,'SELECT canonical_event_id,canonical_snapshot_id,updated_at FROM current_scores WHERE entry_id=?',[$entry]);$older=snapshot($pdo,$ids,$entry,$ids['sourceA'],'2026-09-14 14:00:01.000001','CONFIRMED_UTC','1','o',$now);$ids['snapshots'][]=$older;$outAt='2026-09-14 14:01:04.000001';ok($repo->reconcileAcceptedSnapshot($older,$outAt)->outcome==='OUT_OF_ORDER','out-of-order result');$flag=one($pdo,'SELECT * FROM score_snapshot_flags WHERE snapshot_id=?',[$older]);$details=json_decode((string)$flag['details'],true,flags:JSON_THROW_ON_ERROR);$expectedDiagnostic=Sha256::binary('OUT_OF_ORDER|'.$older);ok(countOf($pdo,'SELECT COUNT(*) FROM canonical_score_events WHERE entry_id=?',[$entry])===$beforeEvent,'out-of-order canonical count unchanged');ok((string)scalar($pdo,'SELECT canonical_event_id FROM current_scores WHERE entry_id=?',[$entry])===(string)$beforePointer['canonical_event_id']&&(string)scalar($pdo,'SELECT canonical_snapshot_id FROM current_scores WHERE entry_id=?',[$entry])===(string)$beforePointer['canonical_snapshot_id']&&(string)scalar($pdo,'SELECT updated_at FROM current_scores WHERE entry_id=?',[$entry])===(string)$beforePointer['updated_at'],'out-of-order current pointer unchanged');ok(countOf($pdo,'SELECT COUNT(*) FROM score_snapshot_flags WHERE snapshot_id=?',[$older])===1,'out-of-order flag count');ok((string)$flag['snapshot_id']===$older&&$flag['flag']==='OUT_OF_ORDER','out-of-order flag identity');ok($flag['detected_at']===$outAt,'out-of-order detected at');ok(strlen($flag['diagnostic_fingerprint'])===32,'out-of-order fingerprint length');ok(hash_equals($expectedDiagnostic,$flag['diagnostic_fingerprint']),'out-of-order fingerprint content');ok(is_array($details)&&array_keys($details)===['current_canonical_event_id','current_canonical_snapshot_id','current_effective_at']||is_array($details)&&count(array_diff(array_keys($details),['current_canonical_event_id','current_canonical_snapshot_id','current_effective_at']))===0&&count($details)===3,'out-of-order evidence keys');ok($details['current_canonical_event_id']===(string)$beforePointer['canonical_event_id'],'out-of-order current event evidence');ok($details['current_canonical_snapshot_id']===(string)$beforePointer['canonical_snapshot_id'],'out-of-order current snapshot evidence');ok($details['current_effective_at']==='2026-09-14 14:00:02.000001','out-of-order current effective-at evidence');$scenarios['out_of_order']=true;
    ok($repo->reconcileAcceptedSnapshot($older,'2026-09-14 14:01:05.000001')->outcome==='OUT_OF_ORDER'&&countOf($pdo,'SELECT COUNT(*) FROM score_snapshot_flags WHERE snapshot_id=?',[$older])===1,'out-of-order dedup');$scenarios['out_of_order_dedup']=true;
    $cross=snapshot($pdo,$ids,$entry,$ids['sourceB'],'2026-09-14 14:00:03.000001','CONFIRMED_UTC','999','x',$now);$ids['snapshots'][]=$cross;ok($repo->reconcileAcceptedSnapshot($cross,'2026-09-14 14:01:06.000001')->outcome==='DEFERRED_CROSS_SOURCE_POLICY'&&countOf($pdo,'SELECT COUNT(*) FROM canonical_score_events WHERE score_snapshot_id=?',[$cross])===0&&countOf($pdo,'SELECT COUNT(*) FROM score_snapshot_flags WHERE snapshot_id=?',[$cross])===0,'cross-source deferred');$scenarios['cross_source_deferred']=true;
    $clockCalls=0;$serviceAt='2026-09-14 14:02:00.000001';$service=new NormalizedIngestionService($repo,static function()use(&$clockCalls,$serviceAt):string{$clockCalls++;return $serviceAt;});
    $serviceReceipt=new RedactedReceipt($ids['sourceA'],$ids['contest'],null,null,$now,'SYNTHETIC','GET','/fixture?token=[REDACTED]',200,'application/json',['safe'=>'fixture'],'{"safe":true}',Sha256::binary($tag.'service'),['redacted_keys'=>true],['fixture'=>$tag]);
    $serviceA=new NormalizedScoreObservation($ids['sourceA'],$ids['contest'],$tag.'-service-a',$tag.'-service-a',null,null,'2026-09-14 14:00:10.000001','2026-09-14 14:00:10.000001','CONFIRMED_UTC','10','10','10','1',null,['fixture'=>$tag],[]);
    $serviceB=new NormalizedScoreObservation($ids['sourceA'],$ids['contest'],$tag.'-service-b',$tag.'-service-b',null,null,'2026-09-14 14:00:11.000001','2026-09-14 14:00:11.000001','CONFIRMED_UTC','20','20','20','1',null,['fixture'=>$tag],[]);
    $serviceRejected=new NormalizedScoreObservation($ids['sourceA'],$ids['contest'],$tag.'-service-rejected',$tag.'-service-rejected',$ids['otherCategory'],null,null,null,null,'0','0',null,'0',null,null,[]);
    $serviceResult=$service->ingest($serviceReceipt,[$serviceA,$serviceA,$serviceB,$serviceRejected]);
    $serviceRaw=one($pdo,'SELECT processing_status,observation_count,accepted_count,duplicate_count,rejected_count FROM raw_messages WHERE id=?',[$serviceResult->rawMessageId]);
    $serviceEntries=values($pdo,'SELECT id FROM entries WHERE contest_id=? AND normalized_callsign IN (?,?)',[$ids['contest'],$tag.'-service-a',$tag.'-service-b']);
    $serviceEvents=countOf($pdo,'SELECT COUNT(*) FROM canonical_score_events WHERE entry_id IN (?,?) AND selected_at=?',[$serviceEntries[0],$serviceEntries[1],$serviceAt]);
    ok($serviceResult->status==='PARTIAL'&&$serviceResult->observationCount===4&&$serviceResult->acceptedCount===2&&$serviceResult->duplicateCount===1&&$serviceResult->rejectedCount===1&&$clockCalls===1&&$serviceRaw['processing_status']==='PARTIAL'&&(int)$serviceRaw['observation_count']===4&&(int)$serviceRaw['accepted_count']===2&&(int)$serviceRaw['duplicate_count']===1&&(int)$serviceRaw['rejected_count']===1&&count($serviceEntries)===2&&$serviceEvents===2&&countOf($pdo,'SELECT COUNT(*) FROM entries WHERE contest_id=? AND normalized_callsign=?',[$ids['contest'],$tag.'-service-rejected'])===0,'service orchestration');$scenarios['service_orchestration']=true;
    cleanup($pdo,$ids);$cleaned=true;ok(remaining($pdo,$ids)===0,'cleanup');
} catch (Throwable $error) { if(!$cleaned){try{cleanup($pdo,$ids);ok(remaining($pdo,$ids)===0,'failure cleanup');}catch(Throwable){throw new RuntimeException('Canonical probe failed and fixture cleanup failed.');}} throw $error; }
StructuredLogger::event('PHP_CANONICAL_PROBE_PASS',['fixture'=>$tag,'schema'=>DatabaseSafety::PERCONA57_TEST_DATABASE,'scenarios'=>$scenarios,'timeline'=>['append_only_verified'=>true,'current_pointer_verified'=>true],'out_of_order'=>['diagnostic_fingerprint_bytes'=>32,'flag_count_after_repeat'=>1],'cleanup_remaining_fixture_rows'=>0]);

function setup(PDO $p,array &$i,string $t,string $n):void{$p->prepare("INSERT INTO contests (name,normalized_name,slug,status,created_at,updated_at) VALUES (?,?,?,'SCHEDULED',?,?)")->execute([$t,$t,$t,$n,$n]);$i['contest']=(string)$p->lastInsertId();$p->prepare("INSERT INTO contests (name,normalized_name,slug,status,created_at,updated_at) VALUES (?,?,?,'SCHEDULED',?,?)")->execute([$t.'-other',$t.'-other',$t.'-other',$n,$n]);$i['otherContest']=(string)$p->lastInsertId();$p->prepare("INSERT INTO contest_categories (contest_id,category_key,display_name,active,created_at,updated_at) VALUES (?,'FIXTURE',?,1,?,?)")->execute([$i['otherContest'],$t,$n,$n]);$i['otherCategory']=(string)$p->lastInsertId();foreach(['sourceA','sourceB']as$k){$p->prepare("INSERT INTO sources (code,kind,precedence_rank,display_name,enabled,created_at,updated_at) VALUES (?,'FIXTURE',1,?,1,?,?)")->execute([$t.$k,$t,$n,$n]);$i[$k]=(string)$p->lastInsertId();$p->prepare("INSERT INTO raw_messages (source_id,contest_id,received_at,processing_status,processing_attempts,observation_count,accepted_count,duplicate_count,rejected_count,message_kind,payload_redacted,payload_sha256,created_at) VALUES (?,? ,?,'PROCESSED',1,0,0,0,0,'SYNTHETIC','{}',?,?)")->execute([$i[$k],$i['contest'],$n,Sha256::binary($t.$k),$n]);$i['raw'.substr($k,-1)]=(string)$p->lastInsertId();}}
function entry(PDO $p,array $i,string $call,string $n):string{$p->prepare('INSERT INTO entries (contest_id,normalized_callsign,display_callsign,metadata,created_at,updated_at) VALUES (?,?,?,NULL,?,?)')->execute([$i['contest'],$call,$call,$n,$n]);return(string)$p->lastInsertId();}
function snapshot(PDO $p,array $i,string $e,string $s,?string $ts,string $q,string $score,string $salt,string $n):string{$raw=$s===$i['sourceA']?$i['rawA']:$i['rawB'];$p->prepare("INSERT INTO score_snapshots (entry_id,contest_id,source_id,raw_message_id,source_timestamp,source_timestamp_quality,received_at,score,qso_total,mult_total,normalized_fingerprint,acceptance_status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,'ACCEPTED',?)")->execute([$e,$i['contest'],$s,$raw,$ts,$q,$n,$score,$score,$score,Sha256::binary('snapshot|'.$salt),$n]);return(string)$p->lastInsertId();}
function cleanup(PDO $p,array $i):void{if($i['contest']===null)return;$p->prepare('DELETE FROM current_scores WHERE entry_id IN (SELECT id FROM entries WHERE contest_id=?)')->execute([$i['contest']]);foreach(['score_snapshot_flags'=>'snapshot_id','canonical_score_events'=>'score_snapshot_id','band_snapshots'=>'snapshot_id']as$t=>$c)$p->prepare("DELETE FROM {$t} WHERE {$c} IN (SELECT id FROM score_snapshots WHERE contest_id=?)")->execute([$i['contest']]);$p->prepare('DELETE FROM score_snapshots WHERE contest_id=?')->execute([$i['contest']]);$p->prepare('DELETE FROM raw_messages WHERE source_id=?')->execute([$i['sourceA']]);foreach(['rawB']as$k)if($i[$k]!==null)$p->prepare('DELETE FROM raw_messages WHERE id=?')->execute([$i[$k]]);$p->prepare('DELETE FROM entries WHERE contest_id=?')->execute([$i['contest']]);$p->prepare('DELETE FROM contest_categories WHERE contest_id=?')->execute([$i['otherContest']]);$p->prepare('DELETE FROM contests WHERE id IN (?,?)')->execute([$i['contest'],$i['otherContest']]);foreach(['sourceA','sourceB']as$k)if($i[$k]!==null)$p->prepare('DELETE FROM sources WHERE id=?')->execute([$i[$k]]);}
function remaining(PDO $p,array $i):int{return countOf($p,'SELECT COUNT(*) FROM contests WHERE id IN (?,?)',[$i['contest'],$i['otherContest']])+countOf($p,'SELECT COUNT(*) FROM contest_categories WHERE id=?',[$i['otherCategory']])+countOf($p,'SELECT COUNT(*) FROM entries WHERE contest_id=?',[$i['contest']])+countOf($p,'SELECT COUNT(*) FROM score_snapshots WHERE contest_id=?',[$i['contest']])+countOf($p,'SELECT COUNT(*) FROM raw_messages WHERE source_id IN (?,?)',[$i['sourceA'],$i['sourceB']])+countOf($p,'SELECT COUNT(*) FROM sources WHERE id IN (?,?)',[$i['sourceA'],$i['sourceB']]);}function one(PDO $p,string $q,array $a):array{$s=$p->prepare($q);$s->execute($a);$v=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($v))throw new RuntimeException('Probe expected row.');return$v;}function scalar(PDO $p,string $q,array $a):string{$s=$p->prepare($q);$s->execute($a);$v=$s->fetchColumn();if(!is_scalar($v))throw new RuntimeException('Probe expected scalar.');return(string)$v;}function countOf(PDO $p,string $q,array $a):int{return(int)scalar($p,$q,$a);}function values(PDO $p,string $q,array $a):array{$s=$p->prepare($q);$s->execute($a);return array_map('strval',$s->fetchAll(PDO::FETCH_COLUMN));}function ok(bool $v,string $n):void{if(!$v)throw new RuntimeException("Probe assertion failed: {$n}");}
