import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import test from "node:test";
import {
  type NormalizedScoreObservation,
  normalizedFingerprint,
  stableJson,
} from "../src/index.js";

interface FixtureVector {
  expected_hex: string;
  observation: Record<string, unknown>;
}

interface ParityFixture {
  canonical_json: { expected: string; input: unknown };
  contest_run_value_conventions: {
    aggregate_band_disagreement: {
      aggregate_is_authoritative: boolean;
      aggregate_qso_total: string;
      band_qso_sum: string;
    };
    callsign: { expected_normalized: string; input: string };
    qtotal_evidence: Record<string, number>;
    soft: Array<{
      expected_fingerprint_evidence: string;
      input: number | string;
    }>;
  };
  normalized_fingerprints: FixtureVector[];
  out_of_order_diagnostic: { expected_hex: string; snapshot_id: string };
  sha256: { expected_hex: string; utf8: string };
}

const fixture = JSON.parse(
  readFileSync(
    new URL(
      "../../../fixtures/parity/collector-php-parity-v1.json",
      import.meta.url,
    ),
    "utf8",
  ),
) as ParityFixture;

test("language-neutral PHP parity fixtures remain generated by the TypeScript reference", () => {
  assert.equal(
    createHash("sha256").update(fixture.sha256.utf8, "utf8").digest("hex"),
    fixture.sha256.expected_hex,
  );
  assert.equal(
    stableJson(fixture.canonical_json.input),
    fixture.canonical_json.expected,
  );
  for (const vector of fixture.normalized_fingerprints) {
    assert.equal(
      Buffer.from(
        normalizedFingerprint(toObservation(vector.observation)),
      ).toString("hex"),
      vector.expected_hex,
    );
  }
  assert.equal(
    createHash("sha256")
      .update(
        `OUT_OF_ORDER|${fixture.out_of_order_diagnostic.snapshot_id}`,
        "utf8",
      )
      .digest("hex"),
    fixture.out_of_order_diagnostic.expected_hex,
  );
});

test("parity fixture records the committed contest.run source-value conventions", () => {
  const conventions = fixture.contest_run_value_conventions;
  assert.equal(
    conventions.callsign.input.trim().toUpperCase(),
    conventions.callsign.expected_normalized,
  );
  assert.deepEqual(
    conventions.soft.map((entry) => String(entry.input)),
    conventions.soft.map((entry) => entry.expected_fingerprint_evidence),
  );
  assert.deepEqual(conventions.qtotal_evidence, {
    qtotalc: 12,
    qtotalp: 34,
    qtotalr: 56,
  });
  assert.equal(
    conventions.aggregate_band_disagreement.aggregate_qso_total,
    "342",
  );
  assert.equal(conventions.aggregate_band_disagreement.band_qso_sum, "30");
  assert.equal(
    conventions.aggregate_band_disagreement.aggregate_is_authoritative,
    true,
  );
});

function toObservation(
  value: Record<string, unknown>,
): NormalizedScoreObservation {
  return {
    sourceId: requiredString(value, "source_id"),
    contestId: requiredString(value, "contest_id"),
    normalizedCallsign: requiredString(value, "normalized_callsign"),
    displayCallsign: requiredString(value, "normalized_callsign"),
    categoryId: nullableString(value.category_id),
    categoryRaw:
      value.category_raw as NormalizedScoreObservation["categoryRaw"],
    sourceTimestamp: nullableString(value.source_timestamp),
    sourceTimestampRaw: nullableString(value.source_timestamp_raw),
    sourceTimestampQuality: nullableString(value.source_timestamp_quality),
    score: nullableString(value.score),
    qsoTotal: nullableString(value.qso_total),
    pointsTotal: nullableString(value.points_total),
    multTotal: nullableString(value.mult_total),
    rawMetrics: null,
    fingerprintEvidence:
      value.source_evidence as NormalizedScoreObservation["fingerprintEvidence"],
    bands: value.bands as NormalizedScoreObservation["bands"],
  };
}

function requiredString(value: Record<string, unknown>, key: string): string {
  const field = value[key];
  if (typeof field !== "string")
    throw new Error(`Fixture ${key} must be a string.`);
  return field;
}

function nullableString(value: unknown): string | null {
  if (value === null || typeof value === "string") return value;
  throw new Error("Fixture value must be string or null.");
}
